name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and pack the project
        run: dotnet pack -c Release --no-build -o ./output

      - name: Publish the package to GitHub Packages
        run: dotnet nuget push ./output/*.nupkg --source https://nuget.pkg.github.com/sujitmeshramnashtech/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
